mysql:
  host: localhost
  database-name: database
  username: minecraft
  password: secret

# The location players will be teleported to / spawn at when they join the server.
lobby-spawn-location:
  world: world
  x: 0.0
  y: 80.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0

min-score-to-broadcast-new-record: 50