permissions:
  # Allow a player to join a full lobby when the game is waiting or starting.
  join-full: "abbacaving.join.full"
  # Respawn a player automatically (once per game) if they die and reset their points.
  respawn: "abbacaving.game.respawn"
  # Reload the plugin configurations
  reload: "abbacaving.command.reload"
  # Broadcasts a message to all online players
  broadcast: "abbacaving.command.broadcast"
  # Starts a new game / match
  forcestart: "abbacaving.command.forcestart"
  # Gives the player night vision
  nightvision: "abbacaving.command.nightvision"

mysql:
  host: localhost
  database-name: database
  username: minecraft
  password: secret

# The location players will be teleported to / spawn at when they join the server.
lobby-spawn-location:
  world: world
  x: 0.0
  y: 80.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0

min-score-to-broadcast-new-record: 50