mysql:
  host: localhost
  database-name: database
  username: minecraft
  password: secret

# The location players will be teleported to / spawn at when they join the server.
lobby-spawn-location:
  world: world
  x: 0.0
  y: 80.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0

min-score-to-broadcast-new-record: 50

cosmetics:
  weapons:
    textaxe:
      custom_model_data: 0
      display_name: "<dark_aqua>Testaxe"
      material: DIAMOND_PICKAXE
      permission: abbacaving.weapon.testaxe # Removing this defaults to abbacaving.weapon.[key]
      lore:
        - One
        - Two
        - Three
  armor:
    testplate:
      display_name: "<gold>Testplate"
      material: GOLDEN_CHESTPLATE