permissions:
  # Allow a player to join a full lobby when the game is waiting or starting.
  join-full: "abbacaving.join.full"
  # Respawn a player automatically (once per game) if they die and reset their points.
  respawn: "abbacaving.game.respawn"

mysql:
  host: localhost
  database-name: database
  username: minecraft
  password: secret

# The location players will be teleported to / spawn at when they join the server.
lobby-spawn-location:
  world: world
  x: 0.0
  y: 80.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0

cave-generator:
  generator-mode: false
  enabled: false # if false, use the pre-built maps
  sxz: 400      # Horizontal stretch (larger number = wider cave)
  sy: 90        # Vertical stretch (larger number = taller cave)
  cutoff: 62    # Minimum Perlin density cutoff (-100 to 100)
  miny: 6       # Lower bound of cave zone
  maxy: 50      # Upper bound of cave zone
  border-size: 750
  spawn-spacing: 50
  spawns: 50

# If specified, load map archives from this directory (absolute path).
maps-directory: /home/minecraft/GenServers/AbbaGen/output/maps
# If specified, load spawn locations from this YAML file (absolute path).
spawns-file: /home/minecraft/GenServers/AbbaGen/output/spawns.yml

game:
  max-games: 1
  players-required-to-start: 5
  maximum-players-per-round: 12
  duration-seconds: 120
  start-countdown-seconds: 10
  grace-period-duration-seconds: 60
  # Set protected-spawn-radius to 0 to disable.
  protected-spawn-radius: 0
  player-health: 40
  min-score-to-broadcast-new-record: 50