name: AbbaCaving
main: com.gamersafer.minecraft.abbacaving.AbbaCavingPlugin
version: '${version}'
author: GamerSafer
api-version: 1.16
depend: [ RandomTeleport, ItemsAdder ]
softdepend: [ PlaceholderAPI, RandomTeleport ]
commands:
  acreload:
    description: Reloads the configuration.
    permission: abbacaving.reload
  aclookup:
    description: Looks up stats for a specific round.
    permission: abbacaving.aclookup
  bcastnp:
    description: Broadcast a message.
    permission: abbacaving.broadcast
    aliases: [ bcast ]
  cosmetics:
    description: Opens Cosmetics GUI
    permission: abbacaving.cosmetics
  forcestart:
    description: Force starts the game.
    permission: abbacaving.forcestart
    permission-message: You are not allowed to do this.
    aliases: [ fs ]
  join:
    description: Joins a game lobby.
    permission: abbacaving.join
    permission-message: You are not allowed to join lobbies.
  leave:
    description: Leaves a game lobby.
    permission: abbacaving.leave
    permission-message: You are not allowed to leave lobbies.
  nightvision:
    description: Night vision toggle.
    permission: abbacaving.nightvision
    permission-message: You are not allowed to toggle night vision.
    aliases: [ nv ]
  stats:
    description: Display a player's stats.
    permission: abbacaving.stats
    permission-message: You are not allowed to view stats.
  points:
    description: Display a player's points.
    permission: abbacaving.points
    permission-message: You are not allowed to view points.
  respawns:
    description: Modify the respawns of a player.
    permission: abbacaving.respawns
    permission-message: You are not allowed to edit respawns.
  debug:
    description: Generic debugging command
    permission: abbacaving.debug
    permission-message: You are not allowed to run debug commands.
  reset:
    description: Reset the command
    permission: abbacaving.reset
    permission-message: You are not allowed to run the reset command.
  save-world:
    description: Toggle world saving
    permission: abbacaving.save-world
    permission-message: You are not allowed to run the save-world command.
  force-save-world:
    description: Delete a player's data
    permission: abbacaving.delete-data
    permission-message: You are not allowed to run the delete-data command.
  delete-data:
    description: Delete a player's data
    permission: abbacaving.delete-data
    permission-message: You are not allowed to run the delete-data command.
permissions:
  abbacaving.*:
    description: Gives access to all Abba Caving permissions.
    children:
      abbacaving.reload: true
      abbacaving.aclookup: true
      abbacaving.broadcast: true
      abbacaving.forcestart: true
      abbacaving.join: true
      abbacaving.join.full: true
      abbacaving.nightvision: true
      abbacaving.stats: true
      abbacaving.points: true
      abbacaving.spectate: true
  abbacaving.join:
    children:
      abbacaving.join.full: false